title: "Francesco Caporali"
url: "https://caporali.github.io"
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
description: "Ph.D. student at Princeton ORFE"
# favicon: true
# favicon_location: "/files/princeton_logo.png"
tracking_id:
footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
sass:
  style: compressed
  sass_dir: _sass
nav:
  - name: "Main"
    link: "/"
  - name: "Resume"
    link: "/files/cv_caporali.pdf"
  - name: "Flashcards"
    link: "/flashcards/flashcards"
  # - name: "Example"
  #   link: "/example"